### ISSUE TITLE
The amount of bugs in this repo is too damn high!

### ISSUE THREAD

**Issue by when-in-rome-dev-1** [software-trizzey/djazzy-vscode#40]
This is a test issue and is not indicative of the actual state of the repo.

<img src="https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExNWx4M3EweWd5MjlsZWtxNWNraHZ5ZWhpdHQwenB6eTdqOGJoajA4YSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/MwrQvTZA9Puuc/giphy.gif" width=420 />

**Comment by software-trizzey** [comment]
Don't worry I squashed em.
